### ISSUE TITLE
DoYouEvenSingelTon^

### ISSUE THREAD

**Issue by FkLaagom** [PGBFDH18/project-3-ludo-web-app-hackerman_web_page#1]
Såg att metoden var under uppbygnad men in case u didnt know:
Blir såhär när man ändrar sitt ursprungliga val av antal spelare.
###   -SourceCodeStealerMan
#   :trollface: :trollface: :trollface: :trollface: :trollface: :trollface: 

![image](https://user-images.githubusercontent.com/46559893/52303303-ef198500-298f-11e9-844d-73053fb9fb5f.png)

![Alt Text](https://media.giphy.com/media/3knKct3fGqxhK/giphy.gif)

**Comment by FkLaagom** [comment]
Denna snippet löser ovanstående. 
```JS
            let element = document.getElementById("players");
            while (element.firstChild) {
                element.removeChild(element.firstChild);
...
```
Lägger den alltså i början av funktionen så den avlivar alla tidigare ungar för att sedan köra resterande del av funktionen som skaffar nya :S 


```JS
        function changingInputs(val) {

            let element = document.getElementById("players");
            while (element.firstChild) {
                element.removeChild(element.firstChild);
            }

            for (var i = 1; i <= val; i++) {
                var h4 = "<h4>Player " + i + " </h4>"
                var id = "<input type='hidden' asp-for='Id' value='" + i + "' />"
                var input = "<input asp-for='Name' type='text' placeholder='Player name' />"
                var select = "<select asp-for='Color'><option value='red'>Red</option><option value='blue'>Blue</option><option value='green'>Green</option><option value='yellow'>Yellow</option></select>"
                $("#players").append(h4, input, select)
            }
        }
```
![image](https://user-images.githubusercontent.com/46559893/52310453-b8e60080-29a3-11e9-839e-e9997d5d50b9.png)

**Comment by Krypt0r7** [comment]
Tack för hjälpen!

Ligger en ny version ute nu.
